# Generated by Django 5.0.2 on 2024-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
