# Generated by Django 5.0.2 on 2024-05-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0006_rename_name_geeksmodel_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
