# Generated by Django 5.0.2 on 2024-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0007_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='title',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='UserName',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
