# Generated by Django 5.2.6 on 2025-10-11 13:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='profit_margin_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
